apiVersion: v1
kind: Pod
metadata: 
  name: {{name}}
  namespace: default
spec:
  restartPolicy: Always
  containers:
  - name: cpu-container
    image: ushakovstas/test_proc:1.1
  - name: mem-container
    image: ushakovstas/test_proc:2.1
